### PR TITLE
Change the implementation of UDOs to be less of a hack.

### PR DESCRIPTION
**Pull request by SirTony**
This is something I've been meaning to get to for a while. The current implementation feels like a hack and can't be easily used with `require`, as well as requiring special consideration when binding UDOs from .NET to Mond.

The following changes were made to how they're implemented:

- All UDO names are converted to legal identifiers prefixed with `op_`. The name is derived from the operator characters, e.g. `fun (%%)( x ) { ... }` becomes `fun op_PercentPercent( x ) { ... }`. This behaviour is inspired by F#, which uses the same strategy.
- UDOs can be nested inside other statements, and the UDO will be local to that scope and all child scopes like a regular function.
- UDOs can have decorators. This does not interfere with enforcing that the function is either unary or binary.
- The global `__ops` table has been abolished.

In addition, the following related changes were made:

- Using any identifier starting with `op_` will always be loaded as if `MondCompilerOptions.UseImplicitGlobals` is `true` regardless of the actual setting. It does not make UDOs global if `MakeRootDeclarationsGlobal` is `false` though.
- Special classes for binding operators were removed, now `MondModuleBinder` also handles static methods marked with `MondOperatorAttribute`. In the case that a method has both `MondOperatorAttribute` and `MondFunctionAttribute`, the operator attribute takes priority.
- UDO `Expression` objects were removed, there's no special bytecode generation that needs to take place, it's just a regular function call now.
- `FunctionExpression` and `SequenceExpression` no longer know nor care if they're operators or not.
- New test cases to cover nesting and decorators for UDOs were added.

As of e71be62, there is new syntax to refer to a UDO by its token when its name is unknown or one wishes to use it as a higher-order function (also similar to F#), for example:

```
fun (#)( x ) -> x.length();

const a = [ "a", "bb", "ccc" ];
const b = a |> Seq.map( (#) ); // [ 1, 2, 3 ]

printLn( (#).getName() ); // op_Hash
```

The `(<operator>)` syntax does not currently work on built-in operators. I feel like it should just to remain consistent, but since the built-in operators aren't functions, doing so could be challenging. What are some thoughts on this?

### CODE REVIEW

**Comment by Rohansi** [comment]
This is better for `require` because they can be properly imported, right?
```
const { op_PercentPercent } = require("Boop.mnd");
```

> Using any identifier starting with `op_` will always be loaded as if `MondCompilerOptions.UseImplicitGlobals` is `true` regardless of the actual setting.

What's the reasoning behind this? I'm not against it, just wondering.

As an extension to this (probably a separate PR), should we support backtick quoted custom operators? That might be a bit of a weird one. I guess the `_op` prefix should only be used only when it wouldn't be a valid identifier.

**Comment by SirTony** [comment]
>This is better for `require` because they can be properly imported, right?

Yep. And even better, e71be62 allows for `const { (%%) } = require( "Boop.mnd" );`

>What's the reasoning behind this? I'm not against it, just wondering.

A bit of a cheat to keep actual implementation as simple as possible by offloading the decision on whether or not to load from `global` elsewhere.

>As an extension to this (probably a separate PR), should we support backtick quoted custom operators? 

I had considered that while working on this. I'm not super into Haskell, but the ability to wrap an ident in backticks to use it as an infix operator is something I really like. Sounds like something worth adding.

**Comment by Rohansi** [comment]
>The `(<operator>)` syntax does not currently work on built-in operators. I feel like it should just to remain consistent, but since the built-in operators aren't functions, doing so could be challenging. What are some thoughts on this?

We could have a module define builtin operator functions in the core libraries. It would just need to export `op_Add` etc right? The parsing would need work too since they wouldn't use the UDO token.

**Comment by SirTony** [comment]
New commits should bring this up to snuff.

All operators that matter _should_ be in the `OperatorModule`. `--` and `++` are suspect since they won't produce their side-effects when called.

**Pull request merged**
